"use client";
import{useEffect,useState}from"react";
export default function Page(){const[ok,setOk]=useState(false),[u,setU]=useState("SMWCAPI"),[p,setP]=useState(""),[data,setData]=useState<any>(null),[name,setName]=useState(""),[detail,setDetail]=useState<any>(null);
 async function load(){const r=await fetch("/api/admin/data");if(r.ok){setOk(true);setData(await r.json())}}
 useEffect(()=>{load()},[]);
 async function login(e:any){e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({username:u,password:p})});if(r.ok)load();else alert("Connexion refusée")}
 async function add(){const r=await fetch("/api/admin/players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name})});const j=await r.json();if(!r.ok)return alert(j.error||"Ajout impossible");setName("");load()}
 async function toggle(id:string,active:boolean){await fetch("/api/admin/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,active:!active})});load()}
 async function rename(id:string,current:string){const next=prompt("Nouveau nom du joueur",current);if(next===null)return;const r=await fetch("/api/admin/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,name:next})});const j=await r.json();if(!r.ok)return alert(j.error||"Modification impossible");load()}
 async function remove(id:string,current:string){if(!confirm(`Supprimer définitivement ${current} ?`))return;const r=await fetch(`/api/admin/players?id=${encodeURIComponent(id)}`,{method:"DELETE"});const j=await r.json();if(!r.ok)return alert(j.error||"Suppression impossible");load()}
 async function history(id:string){const r=await fetch(`/api/admin/matches/${id}`);if(r.ok)setDetail(await r.json())}
 if(!ok)return <form className="card" onSubmit={login}><h2>Administration</h2><input className="input" value={u} onChange={e=>setU(e.target.value)}/><input className="input" type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Mot de passe"/><button className="btn">Connexion</button></form>;
 return <><h2>Administration</h2><div className="card"><h3>Gestion des joueurs</h3><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder="Nouveau joueur"/><button className="btn" onClick={add}>Ajouter</button>{data?.players?.map((x:any)=><div className="matchRow" key={x.id}><span>{x.name} · {x.active?"actif":"inactif"}</span><div style={{display:"flex",gap:7,flexWrap:"wrap"}}><button className="btn secondary" onClick={()=>rename(x.id,x.name)}>Modifier</button><button className="btn secondary" onClick={()=>toggle(x.id,x.active)}>{x.active?"Désactiver":"Activer"}</button><button className="btn danger" onClick={()=>remove(x.id,x.name)}>Supprimer</button></div></div>)}</div><div className="card"><h3>Statistiques globales agrégées</h3><div style={{overflowX:"auto"}}><table><thead><tr><th>Joueur</th><th>Top pts</th><th># T1</th><th># T2</th><th># T3</th><th># Top</th><th># Flops</th><th>Flop pts</th><th># Fantômes</th></tr></thead><tbody>{data?.stats?.map((x:any)=><tr key={x.player_id}><td>{x.name}</td><td>{x.top_points}</td><td>{x.top1_count}</td><td>{x.top2_count}</td><td>{x.top3_count}</td><td>{x.times_top}</td><td>{x.flop_count}</td><td>{x.flop_points}</td><td>{x.ghost_count}</td></tr>)}</tbody></table></div></div><div className="card"><h3>Historique des matchs</h3>{data?.history?.map((x:any)=><p key={x.id}><button className="historyBtn" onClick={()=>history(x.id)}>{x.label}</button> · {new Date(x.played_at).toLocaleDateString("fr-BE")} · {x.ballot_count} bulletin(s) · {x.status}</p>)}</div>{detail&&<div className="card hero"><button className="btn secondary" onClick={()=>setDetail(null)}>Fermer le détail</button><h3>{detail.match?.label}</h3><h4>Résultats</h4>{detail.results?.map((x:any)=><p key={x.player_id}><b>{x.player_name}</b> · Top {x.top_points} · Flop {x.flop_points} {x.is_ghost?"· Fantôme":""}</p>)}<h4>Justifications</h4>{[...new Set((detail.comments||[]).map((x:any)=>x.ballot_id))].map((id:any,i)=><div className="card voteBlock" key={id}><b>Vote anonyme {i+1}</b>{detail.comments.filter((x:any)=>x.ballot_id===id).map((x:any)=><p key={x.kind}>{x.kind.toUpperCase()} · {x.player_name}<br/>{x.comment}</p>)}</div>)}</div>}</>}
